### ISSUE TITLE
fix Identical catch branches error

### ISSUE THREAD

**Issue by akshat-rawat** [jmakhack/hydrate-reminder#349] opened 2022-10-13 20:31 UTC
## Task Context

The Codacy Static Code Analysis system is reporting _Identical catch branches_ errors coming from `CommandInvoker.java.` The reported issues can be found at:

https://app.codacy.com/gh/jmakhack/hydrate-reminder/issues?bid=22863237&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6WyJKYXZhIl19LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlU3R5bGUiXX0seyJpZCI6IkxldmVsIiwidmFsdWVzIjpbIkluZm8iXX0seyJpZCI6IlBhdHRlcm4iLCJ2YWx1ZXMiOlsiNTczMiJdfSx7ImlkIjoiQXV0aG9yIiwidmFsdWVzIjpbXX1d

## Acceptance Criteria / Goals

The goal of this task is to fix _Identical catch branches_ issues reported by Codacy.

## Additional Notes

Please refer to [CONTRIBUTING.md](https://github.com/jmakhack/hydrate-reminder/blob/master/CONTRIBUTING.md) for info on how to setup, build, run, and test this project. Feel free to ping @jmakhack in the comments below with any questions if needed. Also, join the [Discord](https://discord.gg/RTgxfFW9mS) to meet and engage with other contributors!

[<img src="https://img.shields.io/discord/1023562225790767175?color=%20%237289DA&label=discord&logo=discord&logoColor=%20%237289DA&style=for-the-badge" />](https://discord.gg/RTgxfFW9mS)

**Comment by akshat-rawat** [comment] 2022-10-13 20:32
@jmakhack, if it's ok then may I work on this issue?

**Comment by jmakhack** [comment] 2022-10-14 04:17
@akshat-rawat, this is a duplicate of #326.

**Closed by jmakhack** 2022-10-14 04:17 UTC
Labels: best practices
